package cassandra

import (
	"github.com/codeship/clio/lib/cassandra"
	"github.com/codeship/clio/lib/storage"
	"github.com/gocql/gocql"
	"github.com/relops/cqlc/cqlc"
)

// LOGS is the table definition generated by cqlc
var LOGS = cassandra.LogsTableDef()

// Storage wraps a connection to cassandra and implements
// the storage.Storage interface. It can be used to store
// implementations of Line within Cassandra.
type Storage struct {
	session *gocql.Session
}

// Put inserts the implementation of Line in to cassandra.
func (s *Storage) Put(l storage.Line) error {
	tag := l.Tag()
	return cqlc.NewContext().
		Upsert(LOGS).
		SetUUID(LOGS.BUILD_ID, gocql.UUID(tag.BuildID)).
		SetTimestamp(LOGS.CREATED_AT, l.CreatedAt()).
		SetString(LOGS.CONTAINER_ID, tag.ContainerID).
		SetString(LOGS.CONTAINER_NAME, tag.ContainerName).
		SetString(LOGS.PAYLOAD, string(l.Payload())).
		Exec(s.session)
}
